spring:

  datasource:

    url: jdbc:mysql://mysql:3306/e_commerce

    username: root

    password: root

  jpa:

    show-sql: true

    hibernate.ddl-auto: create-drop

  cloud:

    stream:

      bindings:

        OrderEventsChannel:

          destination: OrderEventsChannel

          content-type: application/json

      kafka:

        binder:

          zkNodes: 127.0.0.1

          brokers: 127.0.0.1