spring:

  application:

    name: order-service

  datasource:

    url: jdbc:localhost://localhost:3306/e_commerce

    username: root

    password: root1

  jpa:

    show-sql: true

    hibernate.ddl-auto: update

  cloud:

    stream:

      bindings:

        OrderEventsChannel:

          destination: OrderEventsChannel

          content-type: application/json

          group: OrderEventsChannelQueue

      kafka:

        binder:

          brokers: kafka